#!/usr/bin/env python3
"""
Plot L2 Cache Reuse Distribution

This script generates visualizations of the L2 cache reuse count distribution
from the CSV file generated by FlexiCAS's ReuseCountMonitor.

Usage:
    python3 plot_reuse_dist.py l2_reuse_distribution.csv

Requirements:
    pip install matplotlib pandas numpy
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path


def plot_reuse_distribution(csv_file, output_prefix="l2_reuse"):
    """
    Create comprehensive visualizations of L2 reuse count distribution.
    
    Args:
        csv_file: Path to the l2_reuse_distribution.csv file
        output_prefix: Prefix for output plot files
    """
    # Read the CSV file
    try:
        df = pd.read_csv(csv_file)
    except FileNotFoundError:
        print(f"Error: Could not find {csv_file}")
        print("Make sure you've run a simulation that generates this file.")
        return
    
    print(f"Loaded reuse distribution with {len(df)} entries")
    print(f"Total evictions: {df['Frequency'].sum()}")
    print(f"Max reuse count: {df['ReuseCount'].max()}")
    print(f"Average reuse count: {(df['ReuseCount'] * df['Frequency']).sum() / df['Frequency'].sum():.2f}")
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('L2 Cache Reuse Count Analysis', fontsize=16, fontweight='bold')
    
    # Plot 1: Frequency histogram (bar chart)
    ax1 = axes[0, 0]
    # Limit to first 50 entries for readability
    plot_df = df.head(50) if len(df) > 50 else df
    ax1.bar(plot_df['ReuseCount'], plot_df['Frequency'], color='steelblue', edgecolor='black')
    ax1.set_xlabel('Reuse Count', fontsize=11)
    ax1.set_ylabel('Frequency (Number of Evictions)', fontsize=11)
    ax1.set_title('Reuse Count Histogram', fontsize=12, fontweight='bold')
    ax1.grid(axis='y', alpha=0.3)
    if len(df) > 50:
        ax1.text(0.95, 0.95, f'Showing first 50 of {len(df)} entries',
                transform=ax1.transAxes, ha='right', va='top',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Plot 2: Cumulative distribution function (CDF)
    ax2 = axes[0, 1]
    ax2.plot(df['ReuseCount'], df['CumulativePercentage'], 'r-', linewidth=2)
    ax2.set_xlabel('Reuse Count', fontsize=11)
    ax2.set_ylabel('Cumulative Percentage (%)', fontsize=11)
    ax2.set_title('Cumulative Distribution Function (CDF)', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 105])
    
    # Add percentile markers
    percentiles = [25, 50, 75, 90, 95]
    for p in percentiles:
        # Find reuse count where cumulative percentage >= p
        idx = df[df['CumulativePercentage'] >= p].index[0]
        reuse_at_p = df.loc[idx, 'ReuseCount']
        ax2.axhline(y=p, color='gray', linestyle='--', alpha=0.5, linewidth=0.8)
        ax2.axvline(x=reuse_at_p, color='gray', linestyle='--', alpha=0.5, linewidth=0.8)
        ax2.plot(reuse_at_p, p, 'ro', markersize=5)
        ax2.text(reuse_at_p, p+2, f'P{p}', fontsize=8)
    
    # Plot 3: Percentage distribution (pie chart for categories)
    ax3 = axes[1, 0]
    
    # Categorize reuse counts
    zero_reuse = df[df['ReuseCount'] == 0]['Frequency'].sum()
    low_reuse = df[(df['ReuseCount'] >= 1) & (df['ReuseCount'] <= 3)]['Frequency'].sum()
    medium_reuse = df[(df['ReuseCount'] >= 4) & (df['ReuseCount'] <= 9)]['Frequency'].sum()
    high_reuse = df[df['ReuseCount'] >= 10]['Frequency'].sum()
    
    categories = ['Zero Reuse\n(0)', 'Low Reuse\n(1-3)', 'Medium Reuse\n(4-9)', 'High Reuse\n(10+)']
    sizes = [zero_reuse, low_reuse, medium_reuse, high_reuse]
    colors = ['#ff9999', '#ffcc99', '#99ccff', '#99ff99']
    explode = (0.05, 0, 0, 0)  # Explode zero reuse slice
    
    ax3.pie(sizes, labels=categories, colors=colors, autopct='%1.1f%%',
            startangle=90, explode=explode, textprops={'fontsize': 10})
    ax3.set_title('Reuse Count Categories', fontsize=12, fontweight='bold')
    
    # Plot 4: Log-scale frequency (for heavy-tailed distributions)
    ax4 = axes[1, 1]
    ax4.semilogy(df['ReuseCount'], df['Frequency'], 'g-', linewidth=2, marker='o', markersize=3)
    ax4.set_xlabel('Reuse Count', fontsize=11)
    ax4.set_ylabel('Frequency (log scale)', fontsize=11)
    ax4.set_title('Log-Scale Frequency Distribution', fontsize=12, fontweight='bold')
    ax4.grid(True, alpha=0.3, which='both')
    
    plt.tight_layout()
    
    # Save the figure
    output_file = f"{output_prefix}_analysis.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\nSaved comprehensive analysis plot to: {output_file}")
    
    # Create a second figure for detailed statistics
    fig2, ax = plt.subplots(figsize=(10, 8))
    ax.axis('off')
    
    # Calculate statistics
    total_evictions = df['Frequency'].sum()
    avg_reuse = (df['ReuseCount'] * df['Frequency']).sum() / total_evictions
    max_reuse = df['ReuseCount'].max()
    zero_reuse_pct = (zero_reuse / total_evictions) * 100
    
    # Find percentiles
    percentile_values = {}
    for p in [25, 50, 75, 90, 95, 99]:
        idx = df[df['CumulativePercentage'] >= p].index[0]
        percentile_values[p] = df.loc[idx, 'ReuseCount']
    
    # Create statistics text
    stats_text = f"""
    L2 CACHE REUSE COUNT STATISTICS
    ════════════════════════════════════════════════════
    
    Overall Metrics:
    ────────────────────────────────────────────────────
    Total Evictions:          {total_evictions:,}
    Average Reuse Count:      {avg_reuse:.2f}
    Maximum Reuse Count:      {max_reuse}
    Zero Reuse Evictions:     {zero_reuse:,} ({zero_reuse_pct:.1f}%)
    
    Reuse Categories:
    ────────────────────────────────────────────────────
    Zero Reuse (0):           {zero_reuse:,} ({zero_reuse/total_evictions*100:.1f}%)
    Low Reuse (1-3):          {low_reuse:,} ({low_reuse/total_evictions*100:.1f}%)
    Medium Reuse (4-9):       {medium_reuse:,} ({medium_reuse/total_evictions*100:.1f}%)
    High Reuse (10+):         {high_reuse:,} ({high_reuse/total_evictions*100:.1f}%)
    
    Percentiles:
    ────────────────────────────────────────────────────
    P25 (25th percentile):    {percentile_values[25]}
    P50 (50th percentile):    {percentile_values[50]}
    P75 (75th percentile):    {percentile_values[75]}
    P90 (90th percentile):    {percentile_values[90]}
    P95 (95th percentile):    {percentile_values[95]}
    P99 (99th percentile):    {percentile_values[99]}
    
    Interpretation:
    ────────────────────────────────────────────────────
    """
    
    # Add interpretation
    if zero_reuse_pct > 50:
        stats_text += "    ⚠️  High zero-reuse rate suggests poor temporal locality\n"
        stats_text += "       Consider: larger L2, cache bypassing, or prefetching\n"
    elif zero_reuse_pct < 20:
        stats_text += "    ✓  Low zero-reuse rate indicates good temporal locality\n"
    
    if avg_reuse > 7:
        stats_text += "    ✓  High average reuse indicates effective cache usage\n"
    elif avg_reuse < 2:
        stats_text += "    ⚠️  Low average reuse suggests undersized L2 or streaming\n"
    
    if high_reuse / total_evictions > 0.3:
        stats_text += "    ✓  Significant high-reuse lines indicate good working set capture\n"
    
    ax.text(0.05, 0.95, stats_text, transform=ax.transAxes,
            fontsize=9, verticalalignment='top', family='monospace',
            bbox=dict(boxstyle='round', facecolor='lightgray', alpha=0.8))
    
    output_stats = f"{output_prefix}_statistics.png"
    plt.savefig(output_stats, dpi=300, bbox_inches='tight')
    print(f"Saved statistics summary to: {output_stats}")
    
    # Show the plots
    plt.show()


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 plot_reuse_dist.py <l2_reuse_distribution.csv>")
        print("\nExample:")
        print("  python3 plot_reuse_dist.py l2_reuse_distribution.csv")
        sys.exit(1)
    
    csv_file = sys.argv[1]
    
    if not Path(csv_file).exists():
        print(f"Error: File '{csv_file}' not found!")
        print("\nMake sure you've run a simulation with FlexiCAS that generates")
        print("the l2_reuse_distribution.csv file.")
        sys.exit(1)
    
    # Extract base name for output files
    output_prefix = Path(csv_file).stem
    
    plot_reuse_distribution(csv_file, output_prefix)
    
    print("\n✓ Analysis complete!")
    print("\nGenerated files:")
    print(f"  - {output_prefix}_analysis.png (comprehensive plots)")
    print(f"  - {output_prefix}_statistics.png (statistics summary)")


if __name__ == "__main__":
    main()
